"use strict";
let estaChovendo = false;
estaChovendo = true;
let idade = 29;
let altura = 1.81;
const nacionalidade = 'brasileira';
const colegas = ['lucas', 'fernanda'];
const tecnologias = ['html', 'css', 'js'];
const notas = [1, 2, 3, 4];
const lista = ['luis', true, 29];
let idadeDaAna = 23;
idadeDaAna = '25 anos';
let dadosDaApi;
dadosDaApi = 10;
dadosDaApi = true;
dadosDaApi = [1, 2, 3];
dadosDaApi = 'string';
